[project]
name = "slangpy-nn"
version = "0.1.0"
description = "A neural network implementation in slang."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "slangpy>=0.36.0",
    "torch>=2.9.1",
    "torchvision>=0.24.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = ["black>=25.9.0"]
